//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
	schema "tidbyt.dev/pixlet/schema"
)

// App defines model for App.
type App struct {
	// Author Author of the app
	Author      string `json:"author"`
	Description string `json:"description"`

	// Id Unique ID of the app
	Id string `json:"id"`

	// Name Name of the app
	Name   string  `json:"name"`
	Schema *Schema `json:"schema,omitempty"`

	// Summary Short summary of the app
	Summary string `json:"summary"`
}

// AppInstanceDetail defines model for AppInstanceDetail.
type AppInstanceDetail struct {
	// AppID Applet ID
	AppID string `json:"app-id"`

	// Config Applet configuration
	Config json.RawMessage `json:"config,omitempty"`

	// Idx App position
	Idx *int `json:"idx,omitempty"`

	// UUID App instance UUID
	UUID *openapi_types.UUID `json:"uuid,omitempty"`
}

// AppInstanceSummary defines model for AppInstanceSummary.
type AppInstanceSummary struct {
	// AppID Applet ID
	AppID string `json:"app-id"`

	// Config Applet configuration
	Config json.RawMessage `json:"config,omitempty"`

	// Idx App position
	Idx *int `json:"idx,omitempty"`
}

// ChannelDetail defines model for ChannelDetail.
type ChannelDetail struct {
	Applets *[]AppInstanceDetail `json:"applets,omitempty"`

	// Comment Comment for the channel
	Comment *string `json:"comment,omitempty"`

	// Name Name of the channel
	Name        string       `json:"name"`
	Subscribers *[]DeviceRef `json:"subscribers,omitempty"`

	// UUID UUID of the channel
	UUID *openapi_types.UUID `json:"uuid,omitempty"`
}

// ChannelRef defines model for ChannelRef.
type ChannelRef struct {
	// Name Name of the channel
	Name *string `json:"name,omitempty"`

	// UUID UUID of the channel
	UUID *openapi_types.UUID `json:"uuid,omitempty"`
}

// ChannelSummary defines model for ChannelSummary.
type ChannelSummary struct {
	// Comment Comment for the channel
	Comment *string `json:"comment,omitempty"`

	// Name Name of the channel
	Name string `json:"name"`

	// UUID UUID of the channel
	UUID *openapi_types.UUID `json:"uuid,omitempty"`
}

// DeviceRef defines model for DeviceRef.
type DeviceRef struct {
	// Name Name of the channel
	Name *string `json:"name,omitempty"`

	// UUID UUID of the device
	UUID *openapi_types.UUID `json:"uuid,omitempty"`
}

// DeviceSummary defines model for DeviceSummary.
type DeviceSummary struct {
	Channel *ChannelRef `json:"channel,omitempty"`

	// Connected Whether the device is currently connected
	Connected *bool `json:"connected,omitempty"`

	// CurrentIP Current IP address if connected
	CurrentIP *string `json:"current-ip,omitempty"`

	// DeviceInfo Device information payload (firmware version, etc.)
	DeviceInfo *map[string]interface{} `json:"device-info,omitempty"`

	// DeviceInfoUpdated When device info was last updated
	DeviceInfoUpdated *time.Time `json:"device-info-updated,omitempty"`

	// LastConnectTime Last connection timestamp
	LastConnectTime *time.Time `json:"last-connect-time,omitempty"`

	// LastDisconnectTime Last disconnection timestamp
	LastDisconnectTime *time.Time `json:"last-disconnect-time,omitempty"`

	// LastIP Last known IP address
	LastIP *string `json:"last-ip,omitempty"`

	// Name Name of the channel
	Name *string `json:"name,omitempty"`

	// UUID UUID of the device
	UUID *openapi_types.UUID `json:"uuid,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code int32 `json:"code"`

	// Message Error message
	Message string `json:"message"`
}

// Location defines model for Location.
type Location struct {
	// Description Full location description (e.g. "Brooklyn, NY, USA")
	Description string `json:"description"`

	// Lat Latitude
	Lat string `json:"lat"`

	// Lng Longitude
	Lng string `json:"lng"`

	// Locality City/locality name
	Locality string `json:"locality"`

	// PlaceID Unique place identifier
	PlaceID string `json:"place_id"`

	// Timezone IANA timezone identifier (e.g. "America/New_York")
	Timezone string `json:"timezone"`
}

// Notification defines model for Notification.
type Notification = SchemaField

// PushAppletRequest defines model for PushAppletRequest.
type PushAppletRequest struct {
	// Applet Applet ID from catalog
	Applet string `json:"applet"`

	// Config Applet configuration
	Config *map[string]interface{} `json:"config,omitempty"`

	// Duration Display duration in seconds (default 15, 0 for indefinite)
	Duration *int `json:"duration,omitempty"`
}

// Schema defines model for Schema.
type Schema = schema.Schema

// SchemaField defines model for SchemaField.
type SchemaField = schema.SchemaField

// SchemaOption defines model for SchemaOption.
type SchemaOption = schema.SchemaOption

// SchemaVisibility defines model for SchemaVisibility.
type SchemaVisibility = schema.SchemaVisibility

// SessionSummary defines model for SessionSummary.
type SessionSummary struct {
	Channel *ChannelRef `json:"channel,omitempty"`
	Device  *DeviceRef  `json:"device,omitempty"`

	// DisplayName Human-readable display name for virtual displays
	DisplayName *string `json:"display-name,omitempty"`

	// Ephemeral True if this is an ephemeral virtual display connection
	Ephemeral *bool `json:"ephemeral,omitempty"`

	// ID Session ID
	ID *uint32 `json:"id,omitempty"`

	// RemoteAddr Remote IP address
	RemoteAddr *string `json:"remote-addr,omitempty"`
}

// DefaultErrorResponse defines model for DefaultErrorResponse.
type DefaultErrorResponse = Error

// GetAppletsParams defines parameters for GetApplets.
type GetAppletsParams struct {
	// Id Id to filter by
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// RenderAppletParams defines parameters for RenderApplet.
type RenderAppletParams struct {
	// Config JSON configuration for the applet
	Config *string `form:"config,omitempty" json:"config,omitempty"`
}

// PatchChannelAppletJSONBody defines parameters for PatchChannelApplet.
type PatchChannelAppletJSONBody struct {
	// Config Applet configuration
	Config json.RawMessage `json:"config,omitempty"`

	// Idx App position
	Idx *int `json:"idx,omitempty"`
}

// PatchChannelJSONBody defines parameters for PatchChannel.
type PatchChannelJSONBody struct {
	// Comment Channel description
	Comment *string `json:"comment,omitempty"`

	// Name Channel name
	Name *string `json:"name,omitempty"`
}

// PushChannelContentMultipartBody defines parameters for PushChannelContent.
type PushChannelContentMultipartBody struct {
	// Duration Display duration in seconds (default 15, 0 for indefinite)
	Duration *int `json:"duration,omitempty"`

	// Image WebP image (max 128KB, must be 64x32)
	Image openapi_types.File `json:"image"`
}

// GetDevicesParams defines parameters for GetDevices.
type GetDevicesParams struct {
	// Fields Comma-separated list of fields to include, or * for all fields. Default excludes device-info.
	Fields *string `form:"fields,omitempty" json:"fields,omitempty"`
}

// CreateDeviceJSONBody defines parameters for CreateDevice.
type CreateDeviceJSONBody struct {
	Channel ChannelRef `json:"channel"`

	// Name Name for the virtual device
	Name string `json:"name"`
}

// GetDeviceByUUIDParams defines parameters for GetDeviceByUUID.
type GetDeviceByUUIDParams struct {
	// Fields Comma-separated list of fields to include, or * for all fields. Default excludes device-info.
	Fields *string `form:"fields,omitempty" json:"fields,omitempty"`
}

// PatchDeviceJSONBody defines parameters for PatchDevice.
type PatchDeviceJSONBody struct {
	Channel *ChannelRef `json:"channel,omitempty"`

	// Name Device name
	Name *string `json:"name,omitempty"`
}

// PushDeviceContentMultipartBody defines parameters for PushDeviceContent.
type PushDeviceContentMultipartBody struct {
	// Duration Display duration in seconds (default 15, 0 for indefinite)
	Duration *int `json:"duration,omitempty"`

	// Image WebP image (max 128KB, must be 64x32)
	Image openapi_types.File `json:"image"`
}

// SearchLocationsParams defines parameters for SearchLocations.
type SearchLocationsParams struct {
	// Q Search query
	Q string `form:"q" json:"q"`

	// Limit Maximum number of results
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateChannelJSONRequestBody defines body for CreateChannel for application/json ContentType.
type CreateChannelJSONRequestBody = ChannelSummary

// CreateChannelAppletJSONRequestBody defines body for CreateChannelApplet for application/json ContentType.
type CreateChannelAppletJSONRequestBody = AppInstanceSummary

// PatchChannelAppletJSONRequestBody defines body for PatchChannelApplet for application/json ContentType.
type PatchChannelAppletJSONRequestBody PatchChannelAppletJSONBody

// PatchChannelJSONRequestBody defines body for PatchChannel for application/json ContentType.
type PatchChannelJSONRequestBody PatchChannelJSONBody

// PushChannelContentJSONRequestBody defines body for PushChannelContent for application/json ContentType.
type PushChannelContentJSONRequestBody = PushAppletRequest

// PushChannelContentMultipartRequestBody defines body for PushChannelContent for multipart/form-data ContentType.
type PushChannelContentMultipartRequestBody PushChannelContentMultipartBody

// CreateDeviceJSONRequestBody defines body for CreateDevice for application/json ContentType.
type CreateDeviceJSONRequestBody CreateDeviceJSONBody

// PatchDeviceJSONRequestBody defines body for PatchDevice for application/json ContentType.
type PatchDeviceJSONRequestBody PatchDeviceJSONBody

// PushDeviceContentJSONRequestBody defines body for PushDeviceContent for application/json ContentType.
type PushDeviceContentJSONRequestBody = PushAppletRequest

// PushDeviceContentMultipartRequestBody defines body for PushDeviceContent for multipart/form-data ContentType.
type PushDeviceContentMultipartRequestBody PushDeviceContentMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List available apps
	// (GET /applets)
	GetApplets(w http.ResponseWriter, r *http.Request, params GetAppletsParams)
	// Get the details of an app
	// (GET /applets/{id})
	GetAppletByID(w http.ResponseWriter, r *http.Request, id string)
	// Render an applet with config
	// (GET /applets/{id}/render)
	RenderApplet(w http.ResponseWriter, r *http.Request, id string, params RenderAppletParams)

	// (GET /channels)
	GetChannels(w http.ResponseWriter, r *http.Request)

	// (POST /channels)
	CreateChannel(w http.ResponseWriter, r *http.Request)

	// (POST /channels/{channelUUID}/applets)
	CreateChannelApplet(w http.ResponseWriter, r *http.Request, channelUUID openapi_types.UUID)

	// (DELETE /channels/{channelUUID}/applets/{appletUUID})
	DeleteChannelApplet(w http.ResponseWriter, r *http.Request, channelUUID openapi_types.UUID, appletUUID openapi_types.UUID)

	// (PATCH /channels/{channelUUID}/applets/{appletUUID})
	PatchChannelApplet(w http.ResponseWriter, r *http.Request, channelUUID openapi_types.UUID, appletUUID openapi_types.UUID)

	// (DELETE /channels/{uuid})
	DeleteChannel(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)

	// (GET /channels/{uuid})
	FindChannelByUUID(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)

	// (PATCH /channels/{uuid})
	PatchChannel(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Clear channel push override
	// (DELETE /channels/{uuid}/push)
	ClearChannelPush(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Push temporary content to channel
	// (POST /channels/{uuid}/push)
	PushChannelContent(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Get configured devices
	// (GET /devices)
	GetDevices(w http.ResponseWriter, r *http.Request, params GetDevicesParams)
	// Create a new virtual device
	// (POST /devices)
	CreateDevice(w http.ResponseWriter, r *http.Request)

	// (DELETE /devices/{uuid})
	DeleteDevice(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)

	// (GET /devices/{uuid})
	GetDeviceByUUID(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID, params GetDeviceByUUIDParams)

	// (PATCH /devices/{uuid})
	PatchDevice(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Clear device push override
	// (DELETE /devices/{uuid}/push)
	ClearDevicePush(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Push temporary content to device
	// (POST /devices/{uuid}/push)
	PushDeviceContent(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Search locations
	// (GET /locations)
	SearchLocations(w http.ResponseWriter, r *http.Request, params SearchLocationsParams)
	// Get location by place ID
	// (GET /locations/{placeId})
	GetLocationByPlaceID(w http.ResponseWriter, r *http.Request, placeId string)
	// Get connected sessions
	// (GET /sessions)
	GetSessions(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetApplets operation middleware
func (siw *ServerInterfaceWrapper) GetApplets(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAppletsParams

	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameter("form", true, false, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApplets(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAppletByID operation middleware
func (siw *ServerInterfaceWrapper) GetAppletByID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAppletByID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RenderApplet operation middleware
func (siw *ServerInterfaceWrapper) RenderApplet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params RenderAppletParams

	// ------------- Optional query parameter "config" -------------

	err = runtime.BindQueryParameter("form", true, false, "config", r.URL.Query(), &params.Config)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "config", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RenderApplet(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetChannels operation middleware
func (siw *ServerInterfaceWrapper) GetChannels(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChannels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateChannel operation middleware
func (siw *ServerInterfaceWrapper) CreateChannel(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateChannel(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateChannelApplet operation middleware
func (siw *ServerInterfaceWrapper) CreateChannelApplet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "channelUUID" -------------
	var channelUUID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "channelUUID", r.PathValue("channelUUID"), &channelUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channelUUID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateChannelApplet(w, r, channelUUID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteChannelApplet operation middleware
func (siw *ServerInterfaceWrapper) DeleteChannelApplet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "channelUUID" -------------
	var channelUUID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "channelUUID", r.PathValue("channelUUID"), &channelUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channelUUID", Err: err})
		return
	}

	// ------------- Path parameter "appletUUID" -------------
	var appletUUID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "appletUUID", r.PathValue("appletUUID"), &appletUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "appletUUID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteChannelApplet(w, r, channelUUID, appletUUID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchChannelApplet operation middleware
func (siw *ServerInterfaceWrapper) PatchChannelApplet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "channelUUID" -------------
	var channelUUID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "channelUUID", r.PathValue("channelUUID"), &channelUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channelUUID", Err: err})
		return
	}

	// ------------- Path parameter "appletUUID" -------------
	var appletUUID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "appletUUID", r.PathValue("appletUUID"), &appletUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "appletUUID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchChannelApplet(w, r, channelUUID, appletUUID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteChannel operation middleware
func (siw *ServerInterfaceWrapper) DeleteChannel(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteChannel(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FindChannelByUUID operation middleware
func (siw *ServerInterfaceWrapper) FindChannelByUUID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FindChannelByUUID(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchChannel operation middleware
func (siw *ServerInterfaceWrapper) PatchChannel(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchChannel(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ClearChannelPush operation middleware
func (siw *ServerInterfaceWrapper) ClearChannelPush(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ClearChannelPush(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PushChannelContent operation middleware
func (siw *ServerInterfaceWrapper) PushChannelContent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PushChannelContent(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDevices operation middleware
func (siw *ServerInterfaceWrapper) GetDevices(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDevicesParams

	// ------------- Optional query parameter "fields" -------------

	err = runtime.BindQueryParameter("form", true, false, "fields", r.URL.Query(), &params.Fields)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "fields", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDevices(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDevice operation middleware
func (siw *ServerInterfaceWrapper) CreateDevice(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDevice(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDevice operation middleware
func (siw *ServerInterfaceWrapper) DeleteDevice(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDevice(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDeviceByUUID operation middleware
func (siw *ServerInterfaceWrapper) GetDeviceByUUID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDeviceByUUIDParams

	// ------------- Optional query parameter "fields" -------------

	err = runtime.BindQueryParameter("form", true, false, "fields", r.URL.Query(), &params.Fields)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "fields", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDeviceByUUID(w, r, uuid, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchDevice operation middleware
func (siw *ServerInterfaceWrapper) PatchDevice(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchDevice(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ClearDevicePush operation middleware
func (siw *ServerInterfaceWrapper) ClearDevicePush(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ClearDevicePush(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PushDeviceContent operation middleware
func (siw *ServerInterfaceWrapper) PushDeviceContent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PushDeviceContent(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchLocations operation middleware
func (siw *ServerInterfaceWrapper) SearchLocations(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchLocationsParams

	// ------------- Required query parameter "q" -------------

	if paramValue := r.URL.Query().Get("q"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "q", r.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchLocations(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLocationByPlaceID operation middleware
func (siw *ServerInterfaceWrapper) GetLocationByPlaceID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "placeId" -------------
	var placeId string

	err = runtime.BindStyledParameterWithOptions("simple", "placeId", r.PathValue("placeId"), &placeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "placeId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLocationByPlaceID(w, r, placeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSessions operation middleware
func (siw *ServerInterfaceWrapper) GetSessions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/applets", wrapper.GetApplets)
	m.HandleFunc("GET "+options.BaseURL+"/applets/{id}", wrapper.GetAppletByID)
	m.HandleFunc("GET "+options.BaseURL+"/applets/{id}/render", wrapper.RenderApplet)
	m.HandleFunc("GET "+options.BaseURL+"/channels", wrapper.GetChannels)
	m.HandleFunc("POST "+options.BaseURL+"/channels", wrapper.CreateChannel)
	m.HandleFunc("POST "+options.BaseURL+"/channels/{channelUUID}/applets", wrapper.CreateChannelApplet)
	m.HandleFunc("DELETE "+options.BaseURL+"/channels/{channelUUID}/applets/{appletUUID}", wrapper.DeleteChannelApplet)
	m.HandleFunc("PATCH "+options.BaseURL+"/channels/{channelUUID}/applets/{appletUUID}", wrapper.PatchChannelApplet)
	m.HandleFunc("DELETE "+options.BaseURL+"/channels/{uuid}", wrapper.DeleteChannel)
	m.HandleFunc("GET "+options.BaseURL+"/channels/{uuid}", wrapper.FindChannelByUUID)
	m.HandleFunc("PATCH "+options.BaseURL+"/channels/{uuid}", wrapper.PatchChannel)
	m.HandleFunc("DELETE "+options.BaseURL+"/channels/{uuid}/push", wrapper.ClearChannelPush)
	m.HandleFunc("POST "+options.BaseURL+"/channels/{uuid}/push", wrapper.PushChannelContent)
	m.HandleFunc("GET "+options.BaseURL+"/devices", wrapper.GetDevices)
	m.HandleFunc("POST "+options.BaseURL+"/devices", wrapper.CreateDevice)
	m.HandleFunc("DELETE "+options.BaseURL+"/devices/{uuid}", wrapper.DeleteDevice)
	m.HandleFunc("GET "+options.BaseURL+"/devices/{uuid}", wrapper.GetDeviceByUUID)
	m.HandleFunc("PATCH "+options.BaseURL+"/devices/{uuid}", wrapper.PatchDevice)
	m.HandleFunc("DELETE "+options.BaseURL+"/devices/{uuid}/push", wrapper.ClearDevicePush)
	m.HandleFunc("POST "+options.BaseURL+"/devices/{uuid}/push", wrapper.PushDeviceContent)
	m.HandleFunc("GET "+options.BaseURL+"/locations", wrapper.SearchLocations)
	m.HandleFunc("GET "+options.BaseURL+"/locations/{placeId}", wrapper.GetLocationByPlaceID)
	m.HandleFunc("GET "+options.BaseURL+"/sessions", wrapper.GetSessions)

	return m
}

type DefaultErrorResponseJSONResponse Error

type GetAppletsRequestObject struct {
	Params GetAppletsParams
}

type GetAppletsResponseObject interface {
	VisitGetAppletsResponse(w http.ResponseWriter) error
}

type GetApplets200JSONResponse []App

func (response GetApplets200JSONResponse) VisitGetAppletsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAppletsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetAppletsdefaultJSONResponse) VisitGetAppletsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetAppletByIDRequestObject struct {
	Id string `json:"id"`
}

type GetAppletByIDResponseObject interface {
	VisitGetAppletByIDResponse(w http.ResponseWriter) error
}

type GetAppletByID200JSONResponse App

func (response GetAppletByID200JSONResponse) VisitGetAppletByIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAppletByID404JSONResponse Error

func (response GetAppletByID404JSONResponse) VisitGetAppletByIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetAppletByIDdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetAppletByIDdefaultJSONResponse) VisitGetAppletByIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type RenderAppletRequestObject struct {
	Id     string `json:"id"`
	Params RenderAppletParams
}

type RenderAppletResponseObject interface {
	VisitRenderAppletResponse(w http.ResponseWriter) error
}

type RenderApplet200ImagewebpResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response RenderApplet200ImagewebpResponse) VisitRenderAppletResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "image/webp")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type RenderApplet404JSONResponse Error

func (response RenderApplet404JSONResponse) VisitRenderAppletResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RenderAppletdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response RenderAppletdefaultJSONResponse) VisitRenderAppletResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetChannelsRequestObject struct {
}

type GetChannelsResponseObject interface {
	VisitGetChannelsResponse(w http.ResponseWriter) error
}

type GetChannels200JSONResponse []ChannelSummary

func (response GetChannels200JSONResponse) VisitGetChannelsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetChannelsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetChannelsdefaultJSONResponse) VisitGetChannelsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateChannelRequestObject struct {
	Body *CreateChannelJSONRequestBody
}

type CreateChannelResponseObject interface {
	VisitCreateChannelResponse(w http.ResponseWriter) error
}

type CreateChannel201JSONResponse ChannelDetail

func (response CreateChannel201JSONResponse) VisitCreateChannelResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateChanneldefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreateChanneldefaultJSONResponse) VisitCreateChannelResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateChannelAppletRequestObject struct {
	ChannelUUID openapi_types.UUID `json:"channelUUID"`
	Body        *CreateChannelAppletJSONRequestBody
}

type CreateChannelAppletResponseObject interface {
	VisitCreateChannelAppletResponse(w http.ResponseWriter) error
}

type CreateChannelApplet201JSONResponse AppInstanceDetail

func (response CreateChannelApplet201JSONResponse) VisitCreateChannelAppletResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateChannelApplet400JSONResponse Error

func (response CreateChannelApplet400JSONResponse) VisitCreateChannelAppletResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateChannelApplet404JSONResponse Error

func (response CreateChannelApplet404JSONResponse) VisitCreateChannelAppletResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateChannelAppletdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreateChannelAppletdefaultJSONResponse) VisitCreateChannelAppletResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteChannelAppletRequestObject struct {
	ChannelUUID openapi_types.UUID `json:"channelUUID"`
	AppletUUID  openapi_types.UUID `json:"appletUUID"`
}

type DeleteChannelAppletResponseObject interface {
	VisitDeleteChannelAppletResponse(w http.ResponseWriter) error
}

type DeleteChannelApplet200Response struct {
}

func (response DeleteChannelApplet200Response) VisitDeleteChannelAppletResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type DeleteChannelAppletdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response DeleteChannelAppletdefaultJSONResponse) VisitDeleteChannelAppletResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type PatchChannelAppletRequestObject struct {
	ChannelUUID openapi_types.UUID `json:"channelUUID"`
	AppletUUID  openapi_types.UUID `json:"appletUUID"`
	Body        *PatchChannelAppletJSONRequestBody
}

type PatchChannelAppletResponseObject interface {
	VisitPatchChannelAppletResponse(w http.ResponseWriter) error
}

type PatchChannelApplet200Response struct {
}

func (response PatchChannelApplet200Response) VisitPatchChannelAppletResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PatchChannelAppletdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response PatchChannelAppletdefaultJSONResponse) VisitPatchChannelAppletResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteChannelRequestObject struct {
	UUID openapi_types.UUID `json:"uuid"`
}

type DeleteChannelResponseObject interface {
	VisitDeleteChannelResponse(w http.ResponseWriter) error
}

type DeleteChannel200Response struct {
}

func (response DeleteChannel200Response) VisitDeleteChannelResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type DeleteChannel409JSONResponse Error

func (response DeleteChannel409JSONResponse) VisitDeleteChannelResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type DeleteChanneldefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response DeleteChanneldefaultJSONResponse) VisitDeleteChannelResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type FindChannelByUUIDRequestObject struct {
	UUID openapi_types.UUID `json:"uuid"`
}

type FindChannelByUUIDResponseObject interface {
	VisitFindChannelByUUIDResponse(w http.ResponseWriter) error
}

type FindChannelByUUID200JSONResponse ChannelDetail

func (response FindChannelByUUID200JSONResponse) VisitFindChannelByUUIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type FindChannelByUUID200ImagewebpResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response FindChannelByUUID200ImagewebpResponse) VisitFindChannelByUUIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "image/webp")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type FindChannelByUUIDdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response FindChannelByUUIDdefaultJSONResponse) VisitFindChannelByUUIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type PatchChannelRequestObject struct {
	UUID openapi_types.UUID `json:"uuid"`
	Body *PatchChannelJSONRequestBody
}

type PatchChannelResponseObject interface {
	VisitPatchChannelResponse(w http.ResponseWriter) error
}

type PatchChannel200Response struct {
}

func (response PatchChannel200Response) VisitPatchChannelResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PatchChanneldefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response PatchChanneldefaultJSONResponse) VisitPatchChannelResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type ClearChannelPushRequestObject struct {
	UUID openapi_types.UUID `json:"uuid"`
}

type ClearChannelPushResponseObject interface {
	VisitClearChannelPushResponse(w http.ResponseWriter) error
}

type ClearChannelPush200Response struct {
}

func (response ClearChannelPush200Response) VisitClearChannelPushResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type ClearChannelPush404JSONResponse Error

func (response ClearChannelPush404JSONResponse) VisitClearChannelPushResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ClearChannelPushdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ClearChannelPushdefaultJSONResponse) VisitClearChannelPushResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type PushChannelContentRequestObject struct {
	UUID          openapi_types.UUID `json:"uuid"`
	JSONBody      *PushChannelContentJSONRequestBody
	MultipartBody *multipart.Reader
}

type PushChannelContentResponseObject interface {
	VisitPushChannelContentResponse(w http.ResponseWriter) error
}

type PushChannelContent200Response struct {
}

func (response PushChannelContent200Response) VisitPushChannelContentResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PushChannelContent400JSONResponse Error

func (response PushChannelContent400JSONResponse) VisitPushChannelContentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PushChannelContent404JSONResponse Error

func (response PushChannelContent404JSONResponse) VisitPushChannelContentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PushChannelContentdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response PushChannelContentdefaultJSONResponse) VisitPushChannelContentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetDevicesRequestObject struct {
	Params GetDevicesParams
}

type GetDevicesResponseObject interface {
	VisitGetDevicesResponse(w http.ResponseWriter) error
}

type GetDevices200JSONResponse []DeviceSummary

func (response GetDevices200JSONResponse) VisitGetDevicesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDevicesdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetDevicesdefaultJSONResponse) VisitGetDevicesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateDeviceRequestObject struct {
	Body *CreateDeviceJSONRequestBody
}

type CreateDeviceResponseObject interface {
	VisitCreateDeviceResponse(w http.ResponseWriter) error
}

type CreateDevice201JSONResponse DeviceSummary

func (response CreateDevice201JSONResponse) VisitCreateDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateDevice400JSONResponse Error

func (response CreateDevice400JSONResponse) VisitCreateDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateDevicedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreateDevicedefaultJSONResponse) VisitCreateDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteDeviceRequestObject struct {
	UUID openapi_types.UUID `json:"uuid"`
}

type DeleteDeviceResponseObject interface {
	VisitDeleteDeviceResponse(w http.ResponseWriter) error
}

type DeleteDevice200Response struct {
}

func (response DeleteDevice200Response) VisitDeleteDeviceResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type DeleteDevicedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response DeleteDevicedefaultJSONResponse) VisitDeleteDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetDeviceByUUIDRequestObject struct {
	UUID   openapi_types.UUID `json:"uuid"`
	Params GetDeviceByUUIDParams
}

type GetDeviceByUUIDResponseObject interface {
	VisitGetDeviceByUUIDResponse(w http.ResponseWriter) error
}

type GetDeviceByUUID200JSONResponse DeviceSummary

func (response GetDeviceByUUID200JSONResponse) VisitGetDeviceByUUIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDeviceByUUIDdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetDeviceByUUIDdefaultJSONResponse) VisitGetDeviceByUUIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type PatchDeviceRequestObject struct {
	UUID openapi_types.UUID `json:"uuid"`
	Body *PatchDeviceJSONRequestBody
}

type PatchDeviceResponseObject interface {
	VisitPatchDeviceResponse(w http.ResponseWriter) error
}

type PatchDevice200Response struct {
}

func (response PatchDevice200Response) VisitPatchDeviceResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PatchDevicedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response PatchDevicedefaultJSONResponse) VisitPatchDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type ClearDevicePushRequestObject struct {
	UUID openapi_types.UUID `json:"uuid"`
}

type ClearDevicePushResponseObject interface {
	VisitClearDevicePushResponse(w http.ResponseWriter) error
}

type ClearDevicePush200Response struct {
}

func (response ClearDevicePush200Response) VisitClearDevicePushResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type ClearDevicePush404JSONResponse Error

func (response ClearDevicePush404JSONResponse) VisitClearDevicePushResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ClearDevicePush409JSONResponse Error

func (response ClearDevicePush409JSONResponse) VisitClearDevicePushResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type ClearDevicePushdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ClearDevicePushdefaultJSONResponse) VisitClearDevicePushResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type PushDeviceContentRequestObject struct {
	UUID          openapi_types.UUID `json:"uuid"`
	JSONBody      *PushDeviceContentJSONRequestBody
	MultipartBody *multipart.Reader
}

type PushDeviceContentResponseObject interface {
	VisitPushDeviceContentResponse(w http.ResponseWriter) error
}

type PushDeviceContent200Response struct {
}

func (response PushDeviceContent200Response) VisitPushDeviceContentResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PushDeviceContent400JSONResponse Error

func (response PushDeviceContent400JSONResponse) VisitPushDeviceContentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PushDeviceContent404JSONResponse Error

func (response PushDeviceContent404JSONResponse) VisitPushDeviceContentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PushDeviceContent409JSONResponse Error

func (response PushDeviceContent409JSONResponse) VisitPushDeviceContentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PushDeviceContentdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response PushDeviceContentdefaultJSONResponse) VisitPushDeviceContentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type SearchLocationsRequestObject struct {
	Params SearchLocationsParams
}

type SearchLocationsResponseObject interface {
	VisitSearchLocationsResponse(w http.ResponseWriter) error
}

type SearchLocations200JSONResponse []Location

func (response SearchLocations200JSONResponse) VisitSearchLocationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SearchLocationsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response SearchLocationsdefaultJSONResponse) VisitSearchLocationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetLocationByPlaceIDRequestObject struct {
	PlaceId string `json:"placeId"`
}

type GetLocationByPlaceIDResponseObject interface {
	VisitGetLocationByPlaceIDResponse(w http.ResponseWriter) error
}

type GetLocationByPlaceID200JSONResponse Location

func (response GetLocationByPlaceID200JSONResponse) VisitGetLocationByPlaceIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLocationByPlaceID404JSONResponse Error

func (response GetLocationByPlaceID404JSONResponse) VisitGetLocationByPlaceIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetLocationByPlaceIDdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetLocationByPlaceIDdefaultJSONResponse) VisitGetLocationByPlaceIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetSessionsRequestObject struct {
}

type GetSessionsResponseObject interface {
	VisitGetSessionsResponse(w http.ResponseWriter) error
}

type GetSessions200JSONResponse []SessionSummary

func (response GetSessions200JSONResponse) VisitGetSessionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSessionsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetSessionsdefaultJSONResponse) VisitGetSessionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List available apps
	// (GET /applets)
	GetApplets(ctx context.Context, request GetAppletsRequestObject) (GetAppletsResponseObject, error)
	// Get the details of an app
	// (GET /applets/{id})
	GetAppletByID(ctx context.Context, request GetAppletByIDRequestObject) (GetAppletByIDResponseObject, error)
	// Render an applet with config
	// (GET /applets/{id}/render)
	RenderApplet(ctx context.Context, request RenderAppletRequestObject) (RenderAppletResponseObject, error)

	// (GET /channels)
	GetChannels(ctx context.Context, request GetChannelsRequestObject) (GetChannelsResponseObject, error)

	// (POST /channels)
	CreateChannel(ctx context.Context, request CreateChannelRequestObject) (CreateChannelResponseObject, error)

	// (POST /channels/{channelUUID}/applets)
	CreateChannelApplet(ctx context.Context, request CreateChannelAppletRequestObject) (CreateChannelAppletResponseObject, error)

	// (DELETE /channels/{channelUUID}/applets/{appletUUID})
	DeleteChannelApplet(ctx context.Context, request DeleteChannelAppletRequestObject) (DeleteChannelAppletResponseObject, error)

	// (PATCH /channels/{channelUUID}/applets/{appletUUID})
	PatchChannelApplet(ctx context.Context, request PatchChannelAppletRequestObject) (PatchChannelAppletResponseObject, error)

	// (DELETE /channels/{uuid})
	DeleteChannel(ctx context.Context, request DeleteChannelRequestObject) (DeleteChannelResponseObject, error)

	// (GET /channels/{uuid})
	FindChannelByUUID(ctx context.Context, request FindChannelByUUIDRequestObject) (FindChannelByUUIDResponseObject, error)

	// (PATCH /channels/{uuid})
	PatchChannel(ctx context.Context, request PatchChannelRequestObject) (PatchChannelResponseObject, error)
	// Clear channel push override
	// (DELETE /channels/{uuid}/push)
	ClearChannelPush(ctx context.Context, request ClearChannelPushRequestObject) (ClearChannelPushResponseObject, error)
	// Push temporary content to channel
	// (POST /channels/{uuid}/push)
	PushChannelContent(ctx context.Context, request PushChannelContentRequestObject) (PushChannelContentResponseObject, error)
	// Get configured devices
	// (GET /devices)
	GetDevices(ctx context.Context, request GetDevicesRequestObject) (GetDevicesResponseObject, error)
	// Create a new virtual device
	// (POST /devices)
	CreateDevice(ctx context.Context, request CreateDeviceRequestObject) (CreateDeviceResponseObject, error)

	// (DELETE /devices/{uuid})
	DeleteDevice(ctx context.Context, request DeleteDeviceRequestObject) (DeleteDeviceResponseObject, error)

	// (GET /devices/{uuid})
	GetDeviceByUUID(ctx context.Context, request GetDeviceByUUIDRequestObject) (GetDeviceByUUIDResponseObject, error)

	// (PATCH /devices/{uuid})
	PatchDevice(ctx context.Context, request PatchDeviceRequestObject) (PatchDeviceResponseObject, error)
	// Clear device push override
	// (DELETE /devices/{uuid}/push)
	ClearDevicePush(ctx context.Context, request ClearDevicePushRequestObject) (ClearDevicePushResponseObject, error)
	// Push temporary content to device
	// (POST /devices/{uuid}/push)
	PushDeviceContent(ctx context.Context, request PushDeviceContentRequestObject) (PushDeviceContentResponseObject, error)
	// Search locations
	// (GET /locations)
	SearchLocations(ctx context.Context, request SearchLocationsRequestObject) (SearchLocationsResponseObject, error)
	// Get location by place ID
	// (GET /locations/{placeId})
	GetLocationByPlaceID(ctx context.Context, request GetLocationByPlaceIDRequestObject) (GetLocationByPlaceIDResponseObject, error)
	// Get connected sessions
	// (GET /sessions)
	GetSessions(ctx context.Context, request GetSessionsRequestObject) (GetSessionsResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetApplets operation middleware
func (sh *strictHandler) GetApplets(w http.ResponseWriter, r *http.Request, params GetAppletsParams) {
	var request GetAppletsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApplets(ctx, request.(GetAppletsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApplets")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAppletsResponseObject); ok {
		if err := validResponse.VisitGetAppletsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAppletByID operation middleware
func (sh *strictHandler) GetAppletByID(w http.ResponseWriter, r *http.Request, id string) {
	var request GetAppletByIDRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAppletByID(ctx, request.(GetAppletByIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAppletByID")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAppletByIDResponseObject); ok {
		if err := validResponse.VisitGetAppletByIDResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RenderApplet operation middleware
func (sh *strictHandler) RenderApplet(w http.ResponseWriter, r *http.Request, id string, params RenderAppletParams) {
	var request RenderAppletRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RenderApplet(ctx, request.(RenderAppletRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RenderApplet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RenderAppletResponseObject); ok {
		if err := validResponse.VisitRenderAppletResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetChannels operation middleware
func (sh *strictHandler) GetChannels(w http.ResponseWriter, r *http.Request) {
	var request GetChannelsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetChannels(ctx, request.(GetChannelsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetChannels")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetChannelsResponseObject); ok {
		if err := validResponse.VisitGetChannelsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateChannel operation middleware
func (sh *strictHandler) CreateChannel(w http.ResponseWriter, r *http.Request) {
	var request CreateChannelRequestObject

	var body CreateChannelJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateChannel(ctx, request.(CreateChannelRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateChannel")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateChannelResponseObject); ok {
		if err := validResponse.VisitCreateChannelResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateChannelApplet operation middleware
func (sh *strictHandler) CreateChannelApplet(w http.ResponseWriter, r *http.Request, channelUUID openapi_types.UUID) {
	var request CreateChannelAppletRequestObject

	request.ChannelUUID = channelUUID

	var body CreateChannelAppletJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateChannelApplet(ctx, request.(CreateChannelAppletRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateChannelApplet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateChannelAppletResponseObject); ok {
		if err := validResponse.VisitCreateChannelAppletResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteChannelApplet operation middleware
func (sh *strictHandler) DeleteChannelApplet(w http.ResponseWriter, r *http.Request, channelUUID openapi_types.UUID, appletUUID openapi_types.UUID) {
	var request DeleteChannelAppletRequestObject

	request.ChannelUUID = channelUUID
	request.AppletUUID = appletUUID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteChannelApplet(ctx, request.(DeleteChannelAppletRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteChannelApplet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteChannelAppletResponseObject); ok {
		if err := validResponse.VisitDeleteChannelAppletResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchChannelApplet operation middleware
func (sh *strictHandler) PatchChannelApplet(w http.ResponseWriter, r *http.Request, channelUUID openapi_types.UUID, appletUUID openapi_types.UUID) {
	var request PatchChannelAppletRequestObject

	request.ChannelUUID = channelUUID
	request.AppletUUID = appletUUID

	var body PatchChannelAppletJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchChannelApplet(ctx, request.(PatchChannelAppletRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchChannelApplet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchChannelAppletResponseObject); ok {
		if err := validResponse.VisitPatchChannelAppletResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteChannel operation middleware
func (sh *strictHandler) DeleteChannel(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request DeleteChannelRequestObject

	request.UUID = uuid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteChannel(ctx, request.(DeleteChannelRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteChannel")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteChannelResponseObject); ok {
		if err := validResponse.VisitDeleteChannelResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// FindChannelByUUID operation middleware
func (sh *strictHandler) FindChannelByUUID(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request FindChannelByUUIDRequestObject

	request.UUID = uuid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.FindChannelByUUID(ctx, request.(FindChannelByUUIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FindChannelByUUID")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(FindChannelByUUIDResponseObject); ok {
		if err := validResponse.VisitFindChannelByUUIDResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchChannel operation middleware
func (sh *strictHandler) PatchChannel(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request PatchChannelRequestObject

	request.UUID = uuid

	var body PatchChannelJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchChannel(ctx, request.(PatchChannelRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchChannel")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchChannelResponseObject); ok {
		if err := validResponse.VisitPatchChannelResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ClearChannelPush operation middleware
func (sh *strictHandler) ClearChannelPush(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request ClearChannelPushRequestObject

	request.UUID = uuid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ClearChannelPush(ctx, request.(ClearChannelPushRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ClearChannelPush")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ClearChannelPushResponseObject); ok {
		if err := validResponse.VisitClearChannelPushResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PushChannelContent operation middleware
func (sh *strictHandler) PushChannelContent(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request PushChannelContentRequestObject

	request.UUID = uuid
	if strings.HasPrefix(r.Header.Get("Content-Type"), "application/json") {

		var body PushChannelContentJSONRequestBody
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
		request.JSONBody = &body
	}
	if strings.HasPrefix(r.Header.Get("Content-Type"), "multipart/form-data") {
		if reader, err := r.MultipartReader(); err != nil {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
			return
		} else {
			request.MultipartBody = reader
		}
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PushChannelContent(ctx, request.(PushChannelContentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PushChannelContent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PushChannelContentResponseObject); ok {
		if err := validResponse.VisitPushChannelContentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDevices operation middleware
func (sh *strictHandler) GetDevices(w http.ResponseWriter, r *http.Request, params GetDevicesParams) {
	var request GetDevicesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDevices(ctx, request.(GetDevicesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDevices")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDevicesResponseObject); ok {
		if err := validResponse.VisitGetDevicesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateDevice operation middleware
func (sh *strictHandler) CreateDevice(w http.ResponseWriter, r *http.Request) {
	var request CreateDeviceRequestObject

	var body CreateDeviceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDevice(ctx, request.(CreateDeviceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDevice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateDeviceResponseObject); ok {
		if err := validResponse.VisitCreateDeviceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteDevice operation middleware
func (sh *strictHandler) DeleteDevice(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request DeleteDeviceRequestObject

	request.UUID = uuid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteDevice(ctx, request.(DeleteDeviceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteDevice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteDeviceResponseObject); ok {
		if err := validResponse.VisitDeleteDeviceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDeviceByUUID operation middleware
func (sh *strictHandler) GetDeviceByUUID(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID, params GetDeviceByUUIDParams) {
	var request GetDeviceByUUIDRequestObject

	request.UUID = uuid
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDeviceByUUID(ctx, request.(GetDeviceByUUIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDeviceByUUID")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDeviceByUUIDResponseObject); ok {
		if err := validResponse.VisitGetDeviceByUUIDResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchDevice operation middleware
func (sh *strictHandler) PatchDevice(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request PatchDeviceRequestObject

	request.UUID = uuid

	var body PatchDeviceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchDevice(ctx, request.(PatchDeviceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchDevice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchDeviceResponseObject); ok {
		if err := validResponse.VisitPatchDeviceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ClearDevicePush operation middleware
func (sh *strictHandler) ClearDevicePush(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request ClearDevicePushRequestObject

	request.UUID = uuid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ClearDevicePush(ctx, request.(ClearDevicePushRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ClearDevicePush")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ClearDevicePushResponseObject); ok {
		if err := validResponse.VisitClearDevicePushResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PushDeviceContent operation middleware
func (sh *strictHandler) PushDeviceContent(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request PushDeviceContentRequestObject

	request.UUID = uuid
	if strings.HasPrefix(r.Header.Get("Content-Type"), "application/json") {

		var body PushDeviceContentJSONRequestBody
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
		request.JSONBody = &body
	}
	if strings.HasPrefix(r.Header.Get("Content-Type"), "multipart/form-data") {
		if reader, err := r.MultipartReader(); err != nil {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
			return
		} else {
			request.MultipartBody = reader
		}
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PushDeviceContent(ctx, request.(PushDeviceContentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PushDeviceContent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PushDeviceContentResponseObject); ok {
		if err := validResponse.VisitPushDeviceContentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SearchLocations operation middleware
func (sh *strictHandler) SearchLocations(w http.ResponseWriter, r *http.Request, params SearchLocationsParams) {
	var request SearchLocationsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SearchLocations(ctx, request.(SearchLocationsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchLocations")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SearchLocationsResponseObject); ok {
		if err := validResponse.VisitSearchLocationsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLocationByPlaceID operation middleware
func (sh *strictHandler) GetLocationByPlaceID(w http.ResponseWriter, r *http.Request, placeId string) {
	var request GetLocationByPlaceIDRequestObject

	request.PlaceId = placeId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLocationByPlaceID(ctx, request.(GetLocationByPlaceIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLocationByPlaceID")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLocationByPlaceIDResponseObject); ok {
		if err := validResponse.VisitGetLocationByPlaceIDResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSessions operation middleware
func (sh *strictHandler) GetSessions(w http.ResponseWriter, r *http.Request) {
	var request GetSessionsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSessions(ctx, request.(GetSessionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSessions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSessionsResponseObject); ok {
		if err := validResponse.VisitGetSessionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xc63Pbtpb/VzDc/ZDsUJaTpju7+ubHTa7vTW1PXLfTaTMdiDyy0IAAA4Cy1Yz+9zt4",
	"8QlKtEorSdtPlgng4OCcH84LID9FCc9yzoApGc0+RQJkzpkE8885LHBB1T+E4OKda9DPE84UMKV/4jyn",
	"JMGKcDb9TXKmn8lkCRnWv/5bwCKaRf81rSaZ2lY5NVSjzWYTRynIRJBcE4lm0S37wPg9Q+A6xI6gYekk",
	"z/WfXPAchCKWT1yoJRf6V5PSiXmO+AKpJSCc51EcqXUO0SySShB2F7UntxRKAm85u0MLLjJN436JFVJL",
	"IjUlCgqlHGSIIkm7rNwy8rEAdHG+gxuGM+iOvsQZ7Bg4TOg3tpfuX2QZFuvuXDdLLhRyzVsn3cSRgI8F",
	"EZBGs5/1sh3/FfWmeGOvqfclLT7/DRKlGTrJ8wsmFWYJnIPChBrNUnq1iGY/b19VbeiNm3gTt0FSFCG9",
	"nOQ5Im4sur29OI/iSCscq2hmh7SXHUcPkzs+sYqKzJDNZrNjRTeVtFvQzfNJD18aYoafbfPrOc71ZAln",
	"C3LXS8g2FwI7RZRrNJs2COKHsLRyLokj4gYRpuAORAcQbm0h0ZwtMWNAH6toN6xfyXZnmp9EQSZ37Ycu",
	"6DYlt1gIvLZbZa6FMAcxnPA5rEgC72DRJRgGi1uaHtEByW6jkNjRIUWGca9x2x28B/L7l9KL+YRnmXMf",
	"TabObIO2uLtW9dlEIgCnV4yuo5kSBQwUUX1XmLYQAirIHBoAqZl5NP3bhdTUP2xz17dMBzJuebNB9sFt",
	"u4QzBomCwOp/XIJagqitHhGJkkIIYIquUTW0XN+ccwqYGcK234TkAQzbNnRxjXCaCpASkUWIXlCobvTF",
	"tY1MNGMTwhbcSDFNjeHF9LomG4vCJg/nbkXM6pNwhnK8phyn6NmCiOweC0ArEJJwFiNQydHzqK3HJl+W",
	"4oXmpMnYpMhT3CdiVsqWLTi6xxJRLBXyQ2p40w8mipjYYZt8Kj5uHZFNHGmiEydhS6TDzFs9r+uixaF7",
	"SYWzfB8mNLEzS+t73duzkBI5gIuq1yiMnJfkGryEoGmmt7F1hc4BU2g0hp2WjeEDBj4NrN50RqattlbC",
	"1DcvA7FEHGUgJb7rJeSbd4WlbkLfPbSMt9xmMN2VBJKDio/XBaWIurGo1oaewdHdEfolOhWcf6BrFqPL",
	"n2J0e3PyS/Q8ZKIpViF1KaKKFIIDWCDU09lK/wieYEpUIOA/I2o99c3IBfCd8TnFCfy6JbUxHRBJgSmy",
	"ICB2AOtad7ehq0b675wFNH1xcnmCfHONdingkwwESfD0Eu5//YmLD0H5tgBRrqSdnJQisgqxUq6xF4LO",
	"JdccVfAZ5upsGvaaAE2j7sZygvKrMH2PGhPVekxIlnOhqijBZ4JxlGO1jGaRIul8rY5SWE1z8kBBOTaM",
	"YK4LubQpwjv4WIBUwRSFgtqSoqCF4BlKsMKU34WwU+Umw31YT97SUUDq2wx/pl4RzV5823GJROYUr5Hv",
	"jghDEhLOUomeuXHoxbcxOjbRJ2EpLAgjCp4PynO0gELwuCmz8lZAV9Pm8KSigYFQolLONohcA4Vdai5A",
	"6Cr+B9ewa6N5AsMAfuNhOxa068sLGHYHlfbiPBZWmBZBQ0iSkEzM04G1oEBo3ZvR9Jljnj8OOlYYV3kf",
	"dOz/7dnN08DsKyLJnHh3snveH6r+3YxhCxqs8saGxFXe4+ytjQhgwjUEJKHgIQAinVZInZ1hibYMthjr",
	"jO6BXmt3mZk9jcdssat8ZB/S0XEgIGTW7ncXWzWFpPs4VD5KnLq/IHhOg0Ncy04lWFbqiyjHPkYnNeGN",
	"qBeQ2v7212H2SapdreAx5S+3AyZhC/fPIsNsIgCnWmp+u5g41LjiFRGqwNQ37EpYnKO/xDYZgnwJGQhM",
	"uxN/LwrQubkp6ROJMENl7/astdwxWBEImXknftSqKfckPM1V2MBYQMYVTHSm1iX/zjTuyuT4HTBP1I44",
	"0dQCdRv9yJcaWqHY9QVSHGWY4TtA1+QB6HdYCfKAJIiVDscxSxv6IYqaGF93RW+wgntjAMuIInpxdHx0",
	"bP0YMJyTaBZ9Yx5ZZBt4TmvF3LtQAPoOVCEYwpTaEpgLFSFFOM81HxrsJli6SKNZ9AbUiaOoZxE4A2VK",
	"uj930o5Ur3dBqAKB5ppzoh9/LMAcaThxGjdehVxtQ/E+bh6mvTw+ftTZ2dD6dajAHAimkWfGbuIy+glR",
	"L/meBk8AN/Xjo+gtkQrhFSbU7F8jet3Dq2/6iaSbHTo0mw/nOZqvkRFrj+ZO12YzbVde/YjN6BFUsvQ6",
	"NHazqcLKnts85OlUulOTXc3hluZeHb96+hPYS67Qa16wdGysvAHlSq4KEyq1oqziu4iZCmApiC3A0c0e",
	"ODpVvCdqaajngq9ICmkzeTRGSni4oR9hfo1IZitITbhZ0hZxj0abY3sMuMXtyf51c3XZWpQ/KsGe25Cl",
	"cvn3H4O2kdX0HuZ5E2GlZ5sTZo9827Q7+LIChrSuhK8e23ZRbTw60Rt4u3hL7jSGWqFUm1W+8Ac78ihk",
	"Fc88xUP4ms7h606340aM6no2cZRzGTo8FIAVIIwY3NeOw5oys53OylZhi16nPF2PBr22nAIYbHDYNAib",
	"jipfjM2ZP+kOKMyIZ5St0UD89JP7dXt7cb6pB3YDdOm2k7+lsV2nw6x2+Kg3YLFrbG813dsPTp15HR9q",
	"oYsvwejPyuRwSAvcq9iKtlcjRlK9pv8U6wDAVrm/SnczYE9NP9kf5qHdWBRUIO0+N89r7qp3f9meX/b+",
	"irdx0F1ggJNKbH98o3c9cZO5qw9jeUKsU5sO/e94ShbrIbq91gT+Vu1T2/BONfRLuKoXqP+EwzeslCDz",
	"QoEc4EOeDu5N46eVNMjA9caCDbu2B+x1tucmD8KuvDC2J+BC160GmRevN8tcimSRJCDloqB0bR3f/z+9",
	"4/NMLLFEtQuUJgtPMGNcoTl4Fkcyh8GkKlRz6MXEa8JSx/np2lmMfXCxpeZ0QFg8SdIQj1kJeKoMMewX",
	"7Z2xLeqvu8M9NW8vtx1Y9eN4pb5buaU5qV+WGXh+7QeHz7H380INMe/hjzxFdw+xYx+fwlNN80Iut7mr",
	"MwpYIMzWCCeKrADpAYivQAiSAuKsgq2rZMoiA8Q0YqirOiLKeY5IlkFKsAK67ubKeha3/mvN0VjR3mdz",
	"dldeQoleGqToGReI8Upy91g6kT4/WNZXop4rtHiKYqNFi8dDAypRb4VMK7xR+UZceORUuULtLA8RhRRk",
	"ORdYELo2IKTUXeqtuXVzXGaOUXsNayG9XT1zkv/ikTd+uaZ72U5rNSuoIjkWaqo5naRY4W12+nNceHM+",
	"P3DJu8LSsww/oBcv/+/fpzHKCmnCu/999fDNy+f1HKY3NGi9S5aF7+o2+w23+FZ7ZqMEA+LDVp/QM8JW",
	"mJLUic5KJ0aS/A4xSkkGTBLOZKw3qN2WfyLbZcyQNyvmZoXRjeLlPjcO1FmZ2mFJ5/jj3HXZYUrOeJbh",
	"iQTdSft7f7SyIEBTE00QltAiBSPv/zH7Qds5236E3JoQPJheEtXefzjqOXKzYz//BYHmuzgDzmzcuyNP",
	"dVvgTa3AAal3JdGwU53yUo7lUS2x0rmktjSFhNSeuAXuC4XOC879O08jRc/73KXa8lqXP9dtLnmn3XRh",
	"tufm/YD42ilcbz8jmIOeE7Tg2ctd8nmPCkYN3foR3TB8jylxlegIVbhKpA+Ot9ISEl9kfcthoq+8ddBC",
	"Uo/kS+c0rIoUeBXzQAKP/yLOcgwjdJgilT+86YOWqVHtu6e/xrrUeJ7V6XH/WpQj8AUdiDSdxShVJmf9",
	"q+tytdC8jNZ3FpmsqB5bY/osKP0qS0wey/Us7SAHO7WJQ+/LP0mhy0HykHUuJHNIyIIkbvLYT0zYHSKq",
	"LHX5Kpivi3frXlZge5S9viKT/XfV6++q11dd9fqLmNP+2ls9A/XfNOi/qXwDWCRLs4fKzmhee2ur/CxC",
	"TpIPIFAZ4jfto6Xztpxvh3V00/r0IZRLfPxjV+y/ww8kKzLEimwO5tNxAmRBzTtDoekoyYhqZC6VdToO",
	"XLs5SNGv/J7FgHqf74ukla1f7sjAc5qrkNUE2vST+SrDxZY3hXT6vWh9ccMm4vO1+/iESbQ7ibhf4ena",
	"f3NiB8quHTHvh/2EYU/sGP9iXiSqlL9F2U50f443ikpA1IFg8CXtK5hbDxFufJ9D7MzWK7kD9qd/i/SJ",
	"C/LW3aBSYIYTCWLlt0ghaDSLpjgn0eb95j8BAAD//04UlbI3VAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
