import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";
import checker from "vite-plugin-checker";
import PrettyModuleClassnames from "vite-plugin-pretty-module-classnames";
import sassDts from "vite-plugin-sass-dts";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    checker({
      typescript: true,
    }),
    PrettyModuleClassnames(),
    sassDts({
      // By default only the `development` mode is enabled, which means that the `d.ts` files are generated only:
      //  - when the `dev` command is running
      //  - and after the source files are changed
      // Let's add the `production` mode so that the `d.ts` files are generated by the `build` command as well.
      enabledMode: ["development", "production"],
      esmExport: true,
    }),
  ],
  server: {
      host: '0.0.0.0',
      port: 4000,
      proxy: {
        '/api': {
	  target: 'http://app:8080',
	  changeOrigin: true,
	  secure: false,
	  configure: (proxy, _options) => {
	              proxy.on('error', (err, _req, _res) => {
              console.log('proxy error', err);
            });
            proxy.on('proxyReq', (_proxyReq, req, _res) => {
              console.log('Sending Request to the Target:', req.method, req.url);
            });
            proxy.on('proxyRes', (proxyRes, req, _res) => {
              console.log('Received Response from the Target:', proxyRes.statusCode, req.url);
            });
          },
	},
	'/ws': {
	    target: 'http://app:8080',
	    ws: true,
	    rewriteWsOrigin: false,
	},
      }
  }
});
